// FINAL
export const inputRegisterUserConfig = [
  // ── STEP 1: Datos personales
  {
    label: "Nombre",
    key: "first_name",
    type: "text",
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Apellido",
    key: "last_name",
    type: "text",
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Fecha de nacimiento",
    key: "birthdate",
    type: "date",
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Rol",
    key: "role_id",
    type: "select",
    options: [{ label: "Cliente", value: 3 }],
    validation: {
      required: { value: true, message: "Debe seleccionar un rol" },
    },
  },
  {
    label: "Género",
    key: "gender_id",
    type: "select",
    options: [
      { label: "Masculino", value: 1 },
      { label: "Femenino", value: 2 },
      { label: "Prefiero no decir", value: 3 },
    ],
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Ocupación",
    key: "occupation_id",
    type: "select",
    options: [
      { label: "Psicólogo", value: 1 },
      { label: "Psiquiatra", value: 2 },
      { label: "Terapeuta", value: 3 },
      { label: "Estudiante", value: 4 },
      { label: "Docente", value: 5 },
      { label: "Ingeniero", value: 6 },
      { label: "Médico", value: 7 },
      { label: "Abogado", value: 8 },
      { label: "Empresario", value: 9 },
    ],
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Estado civil",
    key: "marital_status_id",
    type: "select",
    options: [
      { label: "Soltero", value: 1 },
      { label: "Casado", value: 2 },
      { label: "Divorciado", value: 3 },
      { label: "Viudo", value: 4 },
      { label: "Unión libre", value: 5 },
    ],
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Nivel educativo",
    key: "education_id",
    type: "select",
    options: [
      { label: "Primaria", value: 1 },
      { label: "Secundaria", value: 2 },
      { label: "Bachillerato", value: 3 },
      { label: "Técnico", value: 4 },
      { label: "Universitario", value: 5 },
      { label: "Postgrado", value: 6 },
      { label: "Doctorado", value: 7 },
    ],
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Tipo de identificación",
    key: "identification.type",
    type: "select",
    options: [
      { label: "Cédula", value: "cedula" },
      { label: "Pasaporte", value: "pasaporte" },
      { label: "RUC", value: "ruc" },
    ],
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Número de identificación",
    key: "identification.number",
    type: "text",
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  // ── STEP 2: Datos generales (índices 5–10) ────────────────────────────────
  {
    label: "Tipo de teléfono",
    key: "phone.type",
    type: "select",
    options: [
      { label: "Móvil", value: "movil" },
      { label: "Casa", value: "casa" },
      { label: "Trabajo", value: "trabajo" },
    ],
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Número de teléfono",
    key: "phone.number",
    type: "text",
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "País",
    key: "address.country_id",
    type: "select",
    options: [{ label: "Ecuador", value: 1 }],
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Provincia",
    key: "address.state_id",
    type: "select",
    options: [
      { label: "Azuay", value: 1 },
      { label: "Bolívar", value: 2 },
      { label: "Cañar", value: 3 },
      { label: "Carchi", value: 4 },
      { label: "Chimborazo", value: 5 },
      { label: "Cotopaxi", value: 6 },
      { label: "El Oro", value: 7 },
      { label: "Esmeraldas", value: 8 },
      { label: "Galápagos", value: 9 },
      { label: "Guayas", value: 10 },
      { label: "Imbabura", value: 11 },
      { label: "Loja", value: 12 },
      { label: "Los Ríos", value: 13 },
      { label: "Manabí", value: 14 },
      { label: "Morona Santiago", value: 15 },
      { label: "Napo", value: 16 },
      { label: "Orellana", value: 17 },
      { label: "Pastaza", value: 18 },
      { label: "Pichincha", value: 19 },
      { label: "Santa Elena", value: 20 },
      { label: "Santo Domingo de los Tsáchilas", value: 21 },
      { label: "Sucumbíos", value: 22 },
      { label: "Tungurahua", value: 23 },
      { label: "Zamora Chinchipe", value: 24 },
    ],
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Ciudad",
    key: "address.city_id",
    type: "select",
    options: [
      // Azuay (1)
      { label: "Cuenca", value: 1 },
      { label: "Gualaceo", value: 2 },
      { label: "Paute", value: 3 },
      { label: "Sígsig", value: 4 },
      { label: "Girón", value: 5 },
      // Bolívar (2)
      { label: "Guaranda", value: 6 },
      { label: "Chillanes", value: 7 },
      { label: "Chimbo", value: 8 },
      { label: "Echeandía", value: 9 },
      { label: "San Miguel", value: 10 },
      // Cañar (3)
      { label: "Azogues", value: 11 },
      { label: "Cañar", value: 12 },
      { label: "Biblián", value: 13 },
      { label: "La Troncal", value: 14 },
      { label: "El Tambo", value: 15 },
      // Carchi (4)
      { label: "Tulcán", value: 16 },
      { label: "Montúfar", value: 17 },
      { label: "Espejo", value: 18 },
      { label: "Mira", value: 19 },
      { label: "Bolívar", value: 20 },
      // Chimborazo (5)
      { label: "Riobamba", value: 21 },
      { label: "Alausí", value: 22 },
      { label: "Chambo", value: 23 },
      { label: "Guano", value: 24 },
      { label: "Chunchi", value: 25 },
      // Cotopaxi (6)
      { label: "Latacunga", value: 26 },
      { label: "La Maná", value: 27 },
      { label: "Salcedo", value: 28 },
      { label: "Saquisilí", value: 29 },
      { label: "Pangua", value: 30 },
      // El Oro (7)
      { label: "Machala", value: 31 },
      { label: "Pasaje", value: 32 },
      { label: "Santa Rosa", value: 33 },
      { label: "Huaquillas", value: 34 },
      { label: "Arenillas", value: 35 },
      // Esmeraldas (8)
      { label: "Esmeraldas", value: 36 },
      { label: "Atacames", value: 37 },
      { label: "Quinindé", value: 38 },
      { label: "Muisne", value: 39 },
      { label: "San Lorenzo", value: 40 },
      // Galápagos (9)
      { label: "Puerto Baquerizo Moreno", value: 41 },
      { label: "Puerto Ayora", value: 42 },
      { label: "Puerto Villamil", value: 43 },
      { label: "Santa Cruz", value: 44 },
      { label: "Isabela", value: 45 },
      // Guayas (10)
      { label: "Guayaquil", value: 46 },
      { label: "Samborondón", value: 47 },
      { label: "Daule", value: 48 },
      { label: "Milagro", value: 49 },
      { label: "Durán", value: 50 },
      // Imbabura (11)
      { label: "Ibarra", value: 51 },
      { label: "Otavalo", value: 52 },
      { label: "Cotacachi", value: 53 },
      { label: "Antonio Ante", value: 54 },
      { label: "Urcuquí", value: 55 },
      // Loja (12)
      { label: "Loja", value: 56 },
      { label: "Catamayo", value: 57 },
      { label: "Macará", value: 58 },
      { label: "Cariamanga", value: 59 },
      { label: "Zamora", value: 60 },
      // Los Ríos (13)
      { label: "Babahoyo", value: 61 },
      { label: "Quevedo", value: 62 },
      { label: "Ventanas", value: 63 },
      { label: "Vinces", value: 64 },
      { label: "Baba", value: 65 },
      // Manabí (14)
      { label: "Portoviejo", value: 66 },
      { label: "Manta", value: 67 },
      { label: "Chone", value: 68 },
      { label: "El Carmen", value: 69 },
      { label: "Jipijapa", value: 70 },
      // Morona Santiago (15)
      { label: "Macas", value: 71 },
      { label: "Gualaquiza", value: 72 },
      { label: "Sucúa", value: 73 },
      { label: "Méndez", value: 74 },
      { label: "Palora", value: 75 },
      // Napo (16)
      { label: "Tena", value: 76 },
      { label: "Archidona", value: 77 },
      { label: "El Chaco", value: 78 },
      { label: "Quijos", value: 79 },
      { label: "Carlos Julio Arosemena Tola", value: 80 },
      // Orellana (17)
      { label: "Francisco de Orellana", value: 81 },
      { label: "La Joya de los Sachas", value: 82 },
      { label: "Loreto", value: 83 },
      { label: "Aguarico", value: 84 },
      { label: "Dayuma", value: 85 },
      // Pastaza (18)
      { label: "Puyo", value: 86 },
      { label: "Mera", value: 87 },
      { label: "Santa Clara", value: 88 },
      { label: "Arajuno", value: 89 },
      { label: "Shell", value: 90 },
      // Pichincha (19)
      { label: "Quito", value: 91 },
      { label: "Cayambe", value: 92 },
      { label: "Mejía", value: 93 },
      { label: "Pedro Moncayo", value: 94 },
      { label: "Rumiñahui", value: 95 },
      // Santa Elena (20)
      { label: "Santa Elena", value: 96 },
      { label: "La Libertad", value: 97 },
      { label: "Salinas", value: 98 },
      { label: "Ancón", value: 99 },
      { label: "Chanduy", value: 100 },
      // Santo Domingo de los Tsáchilas (21)
      { label: "Santo Domingo", value: 101 },
      { label: "La Concordia", value: 102 },
      { label: "Valle Hermoso", value: 103 },
      { label: "Alluriquín", value: 104 },
      { label: "Puerto Limón", value: 105 },
      // Sucumbíos (22)
      { label: "Nueva Loja", value: 106 },
      { label: "Shushufindi", value: 107 },
      { label: "Lago Agrio", value: 108 },
      { label: "Putumayo", value: 109 },
      { label: "Gonzalo Pizarro", value: 110 },
      // Tungurahua (23)
      { label: "Ambato", value: 111 },
      { label: "Baños de Agua Santa", value: 112 },
      { label: "Pelileo", value: 113 },
      { label: "Píllaro", value: 114 },
      { label: "Patate", value: 115 },
      // Zamora Chinchipe (24)
      { label: "Zamora", value: 116 },
      { label: "Yantzaza", value: 117 },
      { label: "Zumba", value: 118 },
      { label: "Centinela del Cóndor", value: 119 },
      { label: "El Pangui", value: 120 },
    ],
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Tipo de dirección",
    key: "address.type",
    type: "select",
    options: [
      { label: "Casa", value: "casa" },
      { label: "Trabajo", value: "trabajo" },
      { label: "Otro", value: "otro" },
    ],
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Dirección principal",
    key: "address.primary_address",
    type: "text",
    validation: { required: { value: true, message: "Campo requerido" } },
  },
  {
    label: "Dirección secundaria",
    key: "address.secondary_address",
    type: "text",
    validation: { required: { value: true, message: "Campo requerido" } },
  },

  // ── STEP 3: Seguridad ─────────────────────────────────────────────────────
  {
    label: "Email",
    key: "email",
    type: "email",
    validation: {
      required: { value: true, message: "Campo requerido" },
      pattern: {
        value: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
        message: "Email no válido",
      },
    },
  },
  {
    label: "Contraseña",
    key: "password",
    type: "password",
    validation: {
      required: { value: true, message: "Campo requerido" },
      minLength: { value: 8, message: "Mínimo 8 caracteres" },
    },
  },
  {
    label: "Confirmar Contraseña",
    key: "password_confirmation",
    type: "password",
    validation: {
      required: { value: true, message: "Campo requerido" },
      minLength: { value: 8, message: "Mínimo 8 caracteres" },
    },
  },
];
